# Generated by Django 4.2.5 on 2023-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=30)),
                ('EmailId', models.CharField(default='', max_length=30)),
                ('Contact', models.IntegerField(default='')),
                ('BloodGroup', models.CharField(default='', max_length=30)),
                ('State', models.CharField(default='', max_length=30)),
                ('District', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=30)),
                ('EmailId', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=30)),
                ('ConformPassword', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
