# Generated by Django 4.2.5 on 2023-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donordetails',
            old_name='Username',
            new_name='Fullname',
        ),
        migrations.AddField(
            model_name='donordetails',
            name='DOB',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='Gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
