# Generated by Django 4.2.5 on 2023-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0002_rename_username_donordetails_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='Phonenumber',
            field=models.IntegerField(default=1),
        ),
    ]
