# Generated by Django 4.2.5 on 2023-11-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0007_alter_logindetails_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='Phonenumber',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='Contact',
            field=models.IntegerField(default=1),
        ),
    ]
