# Generated by Django 4.2.5 on 2023-11-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0008_remove_logindetails_phonenumber_logindetails_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='Contact',
        ),
    ]
