# Generated by Django 4.2.5 on 2023-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0009_remove_logindetails_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
    ]
