# Generated by Django 4.2.5 on 2023-11-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0013_alter_donordetails_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(default='', max_length=30)),
                ('Attender_contact_number', models.CharField(default='', max_length=30)),
                ('Blood_Group', models.CharField(default='', max_length=30)),
                ('Units', models.IntegerField(default='')),
                ('Reason', models.CharField(default='', max_length=30)),
                ('State', models.CharField(default='', max_length=30)),
                ('City', models.CharField(default='', max_length=30)),
                ('Hospital', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
