# Generated by Django 4.2.5 on 2023-11-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0014_requestdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetails',
            name='UserName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='requestdetails',
            name='UserPhoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
