# Generated by Django 4.2.5 on 2023-11-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0015_requestdetails_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCampDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganiserName', models.CharField(default='', max_length=50)),
                ('ContactNumber', models.CharField(default='', max_length=10)),
                ('Venue', models.CharField(default='', max_length=100)),
                ('Date', models.CharField(default='', max_length=10)),
                ('Time', models.TimeField(default='')),
            ],
        ),
    ]
