# Generated by Django 4.2.5 on 2023-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_panel', '0016_bloodcampdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcampdetails',
            name='Time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
